---
services:
  client:
    build:
      context: .
    ports:
      - "8282:8282"
      - "9282:9282"
    volumes:
      - ./root.crt:/usr/local/share/ca-certificates/rparliament.crt:ro
    environment:
      - INTERVAL=120
      - RTR_DOMAIN=node.rparliament.org
